### ISSUE TITLE
Default resource request too low

### ISSUE THREAD

**Issue by salaboy** [zeebe-io/zeebe-kubernetes#4]
Hi everyone, 
Can we raise the default resources request: 

https://github.com/zeebe-io/zeebe-kubernetes/blob/master/45_deployment_operate.yml#L23

```
resources:
  requests:
    cpu: 10m
    memory: 256Mi
  limits:
    cpu: 100m
    memory: 512Mi
```

This means "please give me 1% of CPU" and the limit is set to 10% CPU. 
Asking for half CPU (500m) will make more sense and we can do some memory profiling to see how much memory is required by the app regularly.
